services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    restart: always
    ports:
      - "5010:5010"
    volumes:
      - /home/proxy_pool/container:/app
    links:
      - redis
    environment:
      DB_CONN: "redis://@redis:6379/5"
      REDIS_PASSWORD: "password"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 1
  redis:
    image: "redis"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /home/redis/container:/data
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    environment:
      REDIS_PASSWORD: "password"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 1
